name: ros-configurable-master-uri
base: core18
version: '0.1'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  ros:
    plugin: catkin
    source: .
    include-roscore: false
    catkin-packages: []
    stage-packages: [ros-melodic-rostopic]

  wrappers:
    plugin: dump
    source: .

apps:
  rostopic:
    command: bin/rostopic-wrapper.sh
    plugs: [network]
